services:
  drift-base:
    build:
      context: .
      tags:
        - app-drift-base:latest
      secrets:
        - pip-credentials
    ports:
      - "8080:8080"
    env_file:
      - scripts/local.env
    networks:
      - app
      - backend

secrets:
  pip-credentials:
    file: ./.env

networks:
  app:
    name: app
  backend:
    external: true
    name: backend
