version: '3.8'
services:
  drift-base:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - scripts/local.env
    networks:
      - app
      - backend

networks:
  app:
    name: app
  backend:
    external: true
    name: backend
