version: '3.5'
services:
  drift-base:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - local.env
    networks:
      - app
      - backend

networks:
  app:
    name: app
  backend:
    external:
      name: backend
