version: '3.8'
services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend

networks:
  backend:
    name: backend
