version: '3'
services:
  postgres:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"  # Expose for debugging purposes.
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: driftbase
  redis:
    image: redis:latest

  drift-base:
    image: directivegames/drift-base:latest
    restart: always
    environment:
      DB_HOST: postgres
      DRIFT_REDIS_HOST: redis
      DRIFT_POSTGRES_HOST: postgres
      DRIFT_CELERY_HOST: celery
      DRIFT_CONFIG_URL: developer
      DRIFT_TIER: LOCALTIER
      DRIFT_DEFAULT_TENANT: localorg-developer
      FLASK_APP: drift.devapp:app
      FLASK_ENV: development
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command:
      - bash
      - /app/run_local.sh
